#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.init_main_permission = "visitors"
    args.etherpad_instance = "https://annuel2.framapad.org"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    [default.test_upgrade_from.b47fef9]
    name = "Upgrade from 2019.08.07~ynh1"
