test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.init_main_permission = "visitors"
    args.etherpad_instance = "https://annuel2.framapad.org"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    [default.test_upgrade_from.ce19369d]
    name = "Upgrade from 0.0.20180605~ynh3"
    args.domain = "sub.domain.tld"
    args.path = "/"
